apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-k8s-bdm-web
  labels:
    app: django-k8s-bdm-starter
    type: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: django-k8s-bdm-starter
        type: web
    spec:
      containers:
      - name: django-k8s-starter-bdm-web
        image: gcr.io/adept-cosine-156702/bdm-django:v1
        imagePullPolicy: Always
        command: ["python", "/var/www/django/manage.py", "runserver"]
        ports:
        - containerPort: 8000
