apiVersion: v1
kind: Service
metadata:
  name: bdm-service
spec:
  selector:
    app: django-k8s-bdm-starter
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30036
    protocol: TCP
